// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0uzXCcT9OeoypWXG56eOn0hDJ7IjEoY',
    appId: '1:668531664789:web:64cdf991667e15b900389c',
    messagingSenderId: '668531664789',
    projectId: 'shopping-8e6c7',
    authDomain: 'shopping-8e6c7.firebaseapp.com',
    storageBucket: 'shopping-8e6c7.appspot.com',
    measurementId: 'G-XNT9T70EYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ4F3CbLjgg0KtZT4OjT8LIOutp34eieg',
    appId: '1:668531664789:android:4abd5a98c9c6574500389c',
    messagingSenderId: '668531664789',
    projectId: 'shopping-8e6c7',
    storageBucket: 'shopping-8e6c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBiSgZ2QzHlwW26YI-nLo4rYXgkxXwvk',
    appId: '1:668531664789:ios:4238edfbd52f78d200389c',
    messagingSenderId: '668531664789',
    projectId: 'shopping-8e6c7',
    storageBucket: 'shopping-8e6c7.appspot.com',
    iosBundleId: 'com.example.shoppingExam',
  );
}
